/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rwendell' at '1/23/18 11:35 AM' with Gradle 2.6
 *
 * @author rwendell, @date 1/23/18 11:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
